version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - /tmp/docker/elk/log/nginx:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.1
    volumes:
      - /tmp/docker/elk/log/nginx:/etc/logs/nginx
      - ./filebeat/filebeat.yml:/filebeat.yml:ro
      - ./filebeat/certs:/etc/pki/tls/certs
      - ./filebeat/certs:/etc/pki/tls/private
    networks:
      - elk

  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.3.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/conf.d:/usr/share/logstash/pipeline
      - ./logstash/patterns:/usr/share/logstash/patterns
      - ./logstash/certs/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt:ro
      - ./logstash/certs/logstash-beats.key:/etc/pki/tls/private/logstash-beats.key:ro
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    # volumes:
    #   - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    links:
      - elasticsearch:elasticsearch
    environment:
      - "elasticsearch.hosts:http://localhost:9200"
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
